
name: Pull Request CI

on:
  # pull_request:
  #   branches: [ main ]
  push:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build Application
        run: npm run build

      - name: Save Build Folder
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build

  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Unit Test Dependencies
        run: npm i @testing-library/jest-dom @testing-library/react @testing-library/user-event react-scripts

      - name: Run Unit Tests
        run: npm test

  cypress-tests:
    name: Cypress Tests
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download the build folder
        uses: actions/download-artifact@v3
        with:
          name: build
          path: build

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: npm start
          browser: chrome