
name: Pull Request CI

on:
  push:
    branches: [ 3-cleanup-ci-pipeline-for-merges-to-main ]

jobs:
  checkout:
    name: Checkout
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'
      - name: Install dependencies
        run: npm install
  #   - name: Run tests 🧪
  #     run: npm test
